// src/app/components/action-bars/result-templates-table-action-bar/result-templates-table-action-bar.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ResultTemplateService } from 'src/app/services/result-template.service';
import { ResultTemplate } from 'src/app/types/result-template';

@Component({
  selector: 'app-result-templates-table-action-bar',
  templateUrl: './result-templates-table-action-bar.component.html',
  styleUrls: ['./result-templates-table-action-bar.component.scss']
})
export class ResultTemplatesTableActionBarComponent implements OnInit {

  @Input("resutlTemplate") resultTemplate!: ResultTemplate;

  constructor(private readonly resultTemplateService: ResultTemplateService) {
  }

  ngOnInit(): void {
  }

  public add() {
    this.resultTemplateService.registerResultTemplate(this.resultTemplate);
  }

  public delete() {
    if (this.resultTemplate.id)
      this.resultTemplateService.delete(this.resultTemplate.id).subscribe(
        () => {
          this.resultTemplateService.deleteResultTemplate(this.resultTemplate);
        }
      );
  }
}

<div>
    <button
        class="text-blueGray-500 background-transparent font-bold uppercase px-8 py-3 outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
        type="button" (click)="add()">
        <i class="fas fa-plus"></i>
    </button>
    <button
        class="text-red-500 background-transparent font-bold uppercase px-8 py-3 outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
        type="button" (click)="delete()">
        <i class="fas fa-trash"></i>
    </button>
</div>

// src/components/ActionBars/ResultTemplatesTableActionBar.svelte
<script>
  export let result;
  // export let container;
  function addResult(result) {
    // const child = document.createElement("span");
    // child.textContent = result.time.left;
    console.log("add", result);
    // container.appendChild(child);
    /* <div class="flex flex-wrap">
  <div class="w-full px-4">
    <CardResultCreate title="Výsledek z časomíry" />
  </div>
</div> */
  }

  function deleteResultTemplate(id) {
    console.log("delete", id);
  }
</script>

<div>
  <button
    class="text-blueGray-500 background-transparent font-bold uppercase px-8 py-3 outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
    type="button"
    on:click={addResult(result)}
  >
    <i class="fas fa-plus" />
  </button>
  <button
    class="text-red-500 background-transparent font-bold uppercase px-8 py-3 outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
    type="button"
    on:click={deleteResultTemplate(result.id)}
  >
    <i class="fas fa-trash" />
  </button>
</div>
