// src/components/Cards/CardResultCreate.svelte
<script>
  function timeChanged() {
    document.getElementById("final-time").value = Math.max(
      leftTarget,
      rightTarget
    );
  }
  export let title = "Vytvoření výsledku";
  export let leftTarget = "";
  export let rightTarget = "";
  export let finalTime = "";
  export let result = {};
  if (result) {
    if (result.time) {
      if (leftTarget == "" && result.time.left != undefined) {
        leftTarget = result.time.left;
      }
      if (rightTarget == "" && result.time.rightTarget != undefined) {
        rightTarget = result.time.right;
      }
      if (finalTime == "" && result.time.final != undefined) {
        finalTime = result.time.final;
      }
    }
  }
</script>

<div
  class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0"
>
  <div class="rounded-t bg-white mb-0 px-6 py-6">
    <div class="text-center flex justify-between">
      <h6 class="text-blueGray-700 text-xl font-bold">{title}</h6>
    </div>
  </div>
  <div class="flex-auto px-4 lg:px-10 py-10 pt-0">
    <form>
      <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
        Čas
      </h6>
      <div class="flex flex-wrap">
        <div class="w-full lg:w-4/12 px-4">
          <div class="relative w-full mb-3">
            <label
              class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
              for="left-target"
            >
              Levý terč
            </label>
            <input
              id="left-target"
              type="number"
              class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
              placeholder="0 = N?, 19:23"
              value={leftTarget}
              on:input={timeChanged()}
            />
          </div>
        </div>
        <div class="w-full lg:w-4/12 px-4">
          <div class="relative w-full mb-3">
            <label
              class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
              for="right-target"
            >
              Pravý terč
            </label>
            <input
              id="right-target"
              type="number"
              class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
              placeholder="0 = N?, 23:19"
              value={rightTarget}
              on:input={timeChanged()}
            />
          </div>
        </div>
        <div class="w-full lg:w-4/12 px-4">
          <div class="relative w-full mb-3">
            <label
              class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
              for="final-time"
            >
              Výsledný čas
            </label>
            <input
              id="final-time"
              type="text"
              class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
              placeholder="Vyplní se samo!"
              value={finalTime}
            />
          </div>
        </div>
      </div>

      <hr class="mt-6 border-b-1 border-blueGray-300" />

      <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
        Rozšířené
      </h6>
      <div class="flex flex-wrap">
        <div class="w-full lg:w-12/12 px-4">
          <div class="relative w-full mb-3">
            <label
              class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
              for="grid-about-me"
            >
              About me
            </label>
            <textarea
              id="grid-about-me"
              type="text"
              class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
              rows="4"
              value="A beautiful UI Kit and Admin for Svelte & Tailwind CSS. It is Free
                and Open Source."
            />
          </div>
        </div>
      </div>

      <hr class="mt-6 border-b-1 border-blueGray-300" />

      <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
        Ostatní
      </h6>
      <div class="flex flex-wrap">
        <div class="w-full lg:w-12/12 px-4">
          <div class="relative w-full mb-3">
            <label
              class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
              for="race"
            >
              Závod
            </label>
            <input
              id="race"
              type="text"
              class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
              value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09"
            />
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

// src/app/components/cards/card-result-create/card-result-create.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { CardResultCreateService } from 'src/app/services/card-result-create.service';
import { TeamService } from 'src/app/services/team.service';
import { ResultTemplate } from 'src/app/types/result-template';
import { Team } from 'src/app/types/team';


@Component({
  selector: 'app-card-result-create',
  templateUrl: './card-result-create.component.html',
  styleUrls: ['./card-result-create.component.scss']
})
export class CardResultCreateComponent implements OnInit {

  public resultTemplate?: ResultTemplate;
  //@ts-ignore
  public form: FormGroup;

  public teams: Team[] = [];
  constructor(private readonly cardResultCreateService: CardResultCreateService, private readonly teamService: TeamService) {
    this.cardResultCreateService.resultTemplateAsObservable().subscribe(
      (resultTemplate) => {
        this.resultTemplate = resultTemplate;
        this.setupForm();
      }   
    );

    this.setupForm();
  }
  
  ngOnInit(): void {
    this.teamService.getTeams().subscribe(
      (teams) => {
        this.teams = teams;
      }
    );
  }
  
  public close(){
    this.resultTemplate = undefined;
  }
  
  public setupForm(){
    let final = this.resultTemplate?.time?.final;
    if(!final && this.resultTemplate?.time?.left && this.resultTemplate?.time?.right){
      final = Math.max(this.resultTemplate.time.left, this.resultTemplate.time.right);
    }
    this.form = new FormGroup({
      time: new FormGroup({
        left: new FormControl(this.resultTemplate?.time?.left, [Validators.required]),
        right: new FormControl(this.resultTemplate?.time?.right, [Validators.required]),
        final: new FormControl(final)
      }),
      team: new FormControl()
    });
  }
}

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="absolute z-10 inset-0 overflow-y-auto modal-center" aria-labelledby="modal-title" role="dialog"
    aria-modal="true" *ngIf="resultTemplate || result">
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">

        <div class="absolute inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div
            class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">

            <div
                class="relative flex flex-col min-w-0 break-words w-full shadow-lg rounded-lg bg-blueGray-100 border-0">
                <div class="rounded-t bg-white mb-0 px-6 py-6">
                    <div class="text-center flex justify-between">
                        <h6 class="text-blueGray-700 text-xl font-bold">Nový výsledek</h6>
                        <i role="button" class="fas fa-times text-blueGray-700" (click)="close()"></i>
                    </div>
                </div>
                <div class="flex-auto px-4 lg:px-10 py-10 pt-0">
                    <form [formGroup]="form">
                        <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
                            Čas
                        </h6>
                        <div class="flex flex-wrap" formGroupName="time">
                            <div class="w-full lg:w-4/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                        for="left-target">
                                        Levý terč
                                    </label>
                                    <input id="left-target" type="number"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                        placeholder="0 = N?, 19:23" formControlName="left" />
                                </div>
                            </div>
                            <div class="w-full lg:w-4/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                        for="right-target">
                                        Pravý terč
                                    </label>
                                    <input id="right-target" type="number"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                        placeholder="0 = N?, 23:19" formControlName="right" />
                                </div>
                            </div>
                            <div class="w-full lg:w-4/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                        for="final-time">
                                        Výsledný čas
                                    </label>
                                    <input id="final-time" type="text"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                        placeholder="Vyplní se samo!" formControlName="final" />
                                </div>
                            </div>
                        </div>

                        <hr class="mt-6 border-b-1 border-blueGray-300" />

                        <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
                            Rozšířené
                        </h6>
                        <div class="flex flex-wrap">
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                        for="grid-about-me">
                                        Tým
                                    </label>
                                    <select formControlName="team"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150">
                                        <option selected value="null">Vyberte tým</option>
                                        <option *ngFor="let team of teams" [ngValue]="team.id">
                                            {{team.name}} {{team.category?.name}} ({{team.district?.name}})
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <hr class="mt-6 border-b-1 border-blueGray-300" />

                        <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
                            Ostatní
                        </h6>
                        <div class="flex flex-wrap">
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2" for="race">
                                        Závod
                                    </label>
                                    <select formControlName="race"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150">
                                        <option selected value="null">Vyberte závod</option>
                                        <option *ngFor="let race of races" [ngValue]="race.id">{{race.name}}</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <h6 class="text-blueGray-400 text-sm mt-3 mb-6 font-bold uppercase">
                            Media
                        </h6>
                        <div class="flex flex-wrap" formGroupName="media">
                            <div class="w-full lg:w-4/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                        for="media-yt">
                                        Youtube
                                    </label>
                                    <input id="media-yt" type="text"
                                        class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                        placeholder="https://youtube.com/..." formControlName="youtube" />
                                </div>
                            </div>
                        </div>
                        <div class="flex flex-wrap">
                            <div class="w-full lg:w-12/12 px-4">
                                <button
                                    class="bg-blueGray-700 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                                    (click)="create()">Uložit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
